# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: personal
  theme_night: personal
  font: personal
  font_size: m

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Yibin Wang is a third-year undergraduate in Computer Science at the Huazhong University of Science and Technology. His research interests include adversarial robustness, trustworthy artificial intelligence and machine learning theory.'
    twitter: 'flylee20467405'
  analytics:
    google_analytics: 'G-5V5X93RC4W'
    baidu_tongji: ''
  verification:
    google: 'WQc1e2C1i_sad1HPGq8C7sQ8g7XxheutL2np5dgriCM'
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Yibin Wang. This website is built using [Hugo](https://gohugo.io/) and [Wowchemy](https://wowchemy.com/). '
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - python
      - latex
      - EmacsLisp
    # theme-light: nord
    theme: github-dark
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/flyleeee/hugo-page'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: 'utterances'
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
